### ISSUE TITLE
Improve AuthZ implemention with Casbin

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#1029]
Complexity: 5

Casbin is being used to provide AuthZ for our routes. This works well but there is some duplication we need to handle.

This issue is going to capture small tasks to improve this:

- document the way our route authz works for gRPC and HTTP
- consolidate PublicRoutes with Casbin
	- run Casbin Enforce for a PublicRoutes policy pre-auth and for all Routes post-auth
	- this will require a subset of the policy to run for PublicRoutes
- reformat our configurable custom csv casbin policy into yaml (see below)

Casbin policy could be more readable and declarative instead of comma separated such as:
```yaml
org-admin: &orgAdmin org-admin
auth:
   policy:
      roles:
         - name?: *orgAdmin
           level: 0
           # we could open up flattening for this if we want as the below
           claim: .role 
           claim_value: org-admin
           # the other option would be just leaning into RBAC over auth routes and hardcoding claims
         - role: admin
           level: 1
      route_rules:
         - route: policy*
           actions: *
           roles:
              - *orgAdmin
              - admin
         - route: unsafe*
           actions: *
           roles:
              - *orgAdmin
      public_routes:
         - kas*
         - /kas*
```
