### ISSUE TITLE
ability to map multiple claims to internal platform roles

### ISSUE THREAD

**Issue by strantalis** [opentdf/platform#1031]
Currently, our authentication interceptor configuration allows us to specify only a single claim to map to an internal role. This setup works fine with Keycloak, but as we expand to use other identity providers, we will need the capability to map multiple claims to a given role.

You can refer to the example configuration in the OpenTDF platform.

https://github.com/opentdf/platform/blob/c3828d088a3483b78079cd257b4237291cf7b6f0/opentdf-dev.yaml#L46-L59

**Example Configuration:**

```yaml
policy:
  ## Default policy for all requests
  default: #"role:standard"
  ## Dot notation is used to access nested claims (i.e., realm_access.roles)
  claims:
    - realm_access.roles
    - client_id
    - cid
  map:
    standard:
      - opentdf-client
      - engineering-group
```
