### ISSUE TITLE
new capability to set a platform `mode`

### ISSUE THREAD

**Issue by strantalis** [opentdf/platform#1033]
Currently, when running the platform, we need to explicitly set whether a service is enabled. This works, but as we start to look at running a service like `KAS` independently, we need to consider how to manage this configuration more efficiently. It will become cumbersome if every service within the platform needs to be individually enabled or disabled.

Additionally, not every service requires the same tooling. For example, `KAS` does not need `opa`, yet `opa` is created regardless of the platform configuration. 

https://github.com/opentdf/platform/blob/c3828d088a3483b78079cd257b4237291cf7b6f0/service/pkg/server/start.go#L64-L69

First, we need to define what constitutes the core platform.

**Core Platform:**
  - Well-known (Platform Discovery) Endpoint
  - Policy

The two other services that aren't part of the core are:

**Authorization Service**  
**Key Access Service (KAS)**

If we agree that these are the main services, we can define the following modes:

- **all** - Runs all services as a monolith
- **core**
- **authorization**
- **kas**

As users potentially need to extend or build on top of OpenTDF they could also potentially need to define their own modes as well. This gives us the ability to provide that. So as they add new services under `services` that will essentially become a mode.

Current configuration looks something like this where each service is explicitly defined under the services block. 

https://github.com/opentdf/platform/blob/c3828d088a3483b78079cd257b4237291cf7b6f0/opentdf-dev.yaml#L11-L39

In the new approach, the `enabled` field would be removed as everything would be driven by the `mode`.

https://github.com/opentdf/platform/blob/main/service/pkg/serviceregistry/serviceregistry.go#L22

We wouldn't be required to set defaults for those services like we do today.

https://github.com/opentdf/platform/blob/main/service/internal/config/config.go#L27

#### Example All Mode

```yaml
mode: all
credentials:
  client_id: xxxxxx
  client_secret: xxxxx
db:
  <db config>
services:
  kas:
   <any kas config>
  core:
    <any core config>
  authorization:
    <an authorization config>
```

#### Example Core Mode

```yaml
mode: core # Not sure if we want to call this mode something else?
credentials:
  client_id: xxxxxx
  client_secret: xxxxx
db:
  <db config>
services:
  core:
    <any core config >
```

#### Example KAS Mode

```yaml
mode: kas
credentials:
  client_id: xxxxxx
  client_secret: xxxxx
remote_services:
  core: https://core.opentdf.io:9000
services:
  kas:
    <any core config>
```

As an alternative to having a root-level `remote_services` block, we could also consider the following configuration, although it might be more confusing:

```yaml 
mode: kas
credentials:
  client_id: xxxxxx
  client_secret: xxxxx
services:
  kas:
    core_endpoint: https://core.opentdf.io:9000
    <any core config>
```
