### ISSUE TITLE
YAML Config not properly parsed due to Viper Decoder Config

### ISSUE THREAD

**Issue by 0xArch3r** [opentdf/platform#1247]
Example:

Add the GRPC maxCallSendMsgSize to the server config using the yaml tag specified in the GRPConfig struct, it does not parse it and set that value properly. This is because viper uses mapstructure under the hood. If you add the following to the v.Unmarshal call on line 81 of config.go it will parse the yaml config with the proper values

`err = v.Unmarshal(config, viper.DecoderConfigOption(func(decoderConfig *mapstructure.DecoderConfig) {
		decoderConfig.TagName = "yaml"
	}))`

Without that, viper completely ignores all of the yaml tags specified in all the config structs. It will only parse fields that match the name of the struct (case-insensitive)

**Comment by rodneyxr** [comment]
```go
type GRPCConfig struct {
	// Enable reflection for grpc server (default: true)
	ReflectionEnabled bool `yaml:"reflectionEnabled" default:"true"`

	MaxCallRecvMsgSizeBytes int `yaml:"maxCallRecvMsgSize" default:"4194304"` // 4MB = 4 * 1024 * 1024 = 4194304
	MaxCallSendMsgSizeBytes int `yaml:"maxCallSendMsgSize" default:"4194304"` // 4MB = 4 * 1024 * 1024 = 4194304
}
```

I can confirm trying to set the `maxCallRecvMsgSize` (defined in the yaml tags) in my `opentdf.yaml` did not work.

I had to use the following keys:
```yaml
grpc:
    reflectionEnabled: true # Default is false
    maxCallRecvMsgSizeBytes: 10485760 # 10MB
    maxCallSendMsgSizeBytes: 10485760 # 10MB
```
