### ISSUE TITLE
make cors configurable

### ISSUE THREAD

**Issue by strantalis** [opentdf/platform#305]
Right now the `cors` configuration is hardcoded. This needs to be part of the http server configuration with some sane defaults for the platform

https://github.com/opentdf/platform/blob/main/internal/server/server.go#L124-L131 

Example
```yaml
server
  http:
    cors:
      allowedOrigin:
      allowedMethod:
      .....
```
