### ISSUE TITLE
Endpoint /kas_public_key returns PEM CERTIFICATE instead of PUBLIC KEY

### ISSUE THREAD

**Issue by pflynn-virtru** [opentdf/platform#678]
endpoint is not as expected.

Also, `opentdf.yaml` is not as expected

```yaml
      ec:
        123:
          publicKeyPath: kas-ec-cert.pem
```
