### ISSUE TITLE
Question: should Subject Mappings' Subject Condition Sets values be case-agnostic?

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/platform#718]
Entitlements are sensitive, and we should be as strict as possible. However, there is potential for error and brittle behavior if we do not normalize casing. 

Consider the following example Subject Condition Set mapped to an Attribute Value via a Subject Mapping, which must currently be defined as such if the desire is to capture all likely casing scenarios:

```yaml
  scs_clearance_vp:
    subject_sets:
      - condition_groups:
          - boolean_operator: CONDITION_BOOLEAN_TYPE_ENUM_OR
            conditions:
              - subject_external_selector_value: '.attributes.title[0]'
                operator: SUBJECT_MAPPING_OPERATOR_ENUM_IN
                subject_external_values:
                  - VicePresident
                  - vicepresident
                  - VICEPRESIDENT
```

Without casing normalization, there is even tighter coupling to any identity provider configuration changes or subtle differences among users. We can resolve this by normalizing the `subject_external_values` to upper or lower case.

However, if we normalize to upper or lower case, that is an implicit assumption about access that `vicepresident` and `VICEPRESIDENT` are inherently equal. This seems intuitive and safe, but it should be documented in the protos.
