### ISSUE TITLE
404 (broken link) in primary README

### ISSUE THREAD

**Issue by b-long** [opentdf/platform#736]
The primary README.md has the following content: 

> ### Provisioning Custom Keycloak and Policy Data
> 
> To providion a custom keycloak setup, create a yaml following the format of [the sample keycloak config]((service/cmd/keycloak_data.yaml)). You can create different realms with seperate users, clients, roles, and groups. Run the provisioning with `go run ./service provision keycloak-from-config -f <path-to-your-yaml-file>`.

We should replace the text `((service/cmd/keycloak_data.yaml))`  with `(service/cmd/keycloak_data.yaml)`

While we're on this bit of text, I'm wondering:

1. Do you have any plans to detect broken links?
2. Could we introduce a pre-commit hook or some other linter to prevent spelling errors? (I make them constantly)

One such spell-checker is https://github.com/codespell-project/codespell .

It's very easy to run both locally and in CI, using `pre-commit`, e.g. the following will lint Go, Markdown, and YAML: 

```yaml
# To learn about "pre-commit", see:
#   https://github.com/pre-commit/pre-commit

repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      files: ^.*\.(go|md|yaml)$
      args: ["--write-changes", "--ignore-words-list", "MYCOOLWORD,ANOTHAONE"]
```
